### ISSUE TITLE
Feature idea: point at htaccess-format file

### ISSUE THREAD

**Issue by bigpresh** [odyniec/p5-Dancer-Plugin-Auth-Basic#3]
It strikes me that it would be useful to be able to point the plugin at an Apache-style .htaccess file, for those who may already be maintaining such a file via `htpasswd`.

For example, something like:

```
plugins:
    "Auth::Basic":
        paths:
            "/restricted":
                from_file: '/path/to/htaccess'
```

Just an idea :)

**Comment by odyniec** [comment]
I made [Dancer::Plugin::Auth::Htpasswd](https://github.com/odyniec/Dancer-Plugin-Auth-Htpasswd) for this very purpose. I even wrote a [Dancer Advent Calendar post](http://advent.perldancer.org/2011/13) about it :-)

**Comment by bigpresh** [comment]
Ah, fair point :)
